### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8

### ISSUE THREAD

**Issue by rexwu1104** [KareemRS/heroku-lavalink#14]
error just at title.

I use lavapy to use lavalink, and I get this error.
But I use repl-lavalink, I don't get this error.

**Comment by karyeet** [comment]
Hey,

I was able to successfully use the example shown in the [Lavapy](https://github.com/Aspect1103/Lavapy) readme to play music from my heroku-lavalink server.

Please ensure your pip packages are updated & elaborate on when this error happens.
Feel free to send code samples.

**Comment by rexwu1104** [comment]
![image](https://user-images.githubusercontent.com/44058270/149605866-f300f50a-deab-48ad-afc2-b272e0ba92a7.png)
![image](https://user-images.githubusercontent.com/44058270/149605955-6b63efe4-5f34-4eca-b970-e058d2634511.png)
![image](https://user-images.githubusercontent.com/44058270/149605905-74565e5b-13f4-4929-ac8a-b43cdcf28ff6.png)
![image](https://user-images.githubusercontent.com/44058270/149605969-96848e73-a286-43a0-a8e3-893766a17993.png)

all of these.

**Comment by karyeet** [comment]
This error is not the fault of Lavapy or my release of heroku-lavalink, but the result of incorrect configuration in your fork.

You should **_not change the port in application.yml_** from DYNAMICPORT to your own while hosting on Heroku. 
bootstrap.js will change DYNAMICPORT to the port provided by Heroku in the project environment.
Heroku will not let you bind to any port you provide.

Your project will be available at its URL and it will support both port 80 (http) and port 443 (https). You do not need to configure anything not listed in the readme.

Additionally, you should definitely not set your password in a public github repo, but instead should follow the readme and set your password in the Heroku _config vars_ menu.

I recommend using the One Click Deploy button, as it will guide you through configuration.

If you reconfigure and the issue is resolved, please close this issue.

**Comment by rexwu1104** [comment]
oh, thanks, sorry my english is so poor.
