### ISSUE TITLE
port?

### ISSUE THREAD

**Issue by ghost** [KareemRS/heroku-lavalink#19]
what do i enter the port of the lavalink as?

**Comment by karyeet** [comment]
You don't. 
You will always access your heroku app through port 80 (http) or port 443 (https). 
heroku-lavalink will automatically bind to the internal port provided by heroku.

**Comment by ghost** [comment]
and also is it necessary to link my lavalink url to uptimerobot? coz i think heroku is a deployment service itself, and whenever i link my url to uptimerobot it just shows that 403 forbidden in uptimerobot link dashboard

**Comment by karyeet** [comment]
It is not necessary, but your server may go down if you are using a free dyno.
The purpose of uptimerobot is to keep free dynos from sleeping after 30 minutes of no http activity.

Unless you provide authentication headers and make a valid request with uptimerobot (ex. loadtrack), uptimerobot will always report that the server is down.

I will work on creating a way for the project to visit itself so that external services won't be required.

**Comment by karyeet** [comment]
If you have any further issues regarding this topic feel free to open this back up.
